[package]
name = "csvmutant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.31"
encoding_rs_io = "0.1.7"
csv = "1.1.6"